# Generated by Django 3.1a1 on 2022-07-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales_id', models.IntegerField()),
                ('date_of_purchase', models.DateField()),
                ('customer_id', models.IntegerField()),
                ('fuel', models.CharField(max_length=100)),
                ('vehicle_segment', models.CharField(max_length=1)),
                ('selling_price', models.IntegerField()),
                ('power_steering', models.BooleanField()),
                ('airbags', models.BooleanField()),
                ('sunroof', models.BooleanField()),
                ('matt_finish', models.BooleanField()),
                ('music_system', models.BooleanField()),
                ('customer_gender', models.CharField(max_length=100)),
                ('customer_income_group', models.CharField(max_length=100)),
                ('customer_region', models.CharField(max_length=100)),
                ('customer_marital_status', models.BooleanField()),
            ],
        ),
    ]
