# Generated by Django 4.0.6 on 2022-07-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carsales',
            name='id',
        ),
        migrations.AlterField(
            model_name='carsales',
            name='sales_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
