# Generated by Django 4.0.6 on 2022-07-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_carsales_id_alter_carsales_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsales',
            name='customer_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='carsales',
            name='sales_id',
            field=models.IntegerField(),
        ),
    ]
