# Generated by Django 4.0.6 on 2022-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_carsales_customer_id_alter_carsales_sales_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='carsales',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carsales',
            name='sales_id',
            field=models.IntegerField(),
        ),
    ]
