# Generated by Django 4.0.6 on 2022-07-17 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_carsales_id_alter_carsales_sales_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsales',
            name='date_of_purchase',
            field=models.CharField(max_length=100),
        ),
    ]
