# Generated by Django 4.0.6 on 2022-07-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_carsales_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carsales',
            name='id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='carsales',
            name='sales_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
